repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-case-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: check-file-names
        name: Check file names
        language: python
        entry: python pre_commit_hooks/check_file_names.py
        files: ^Handleiding\/
      - id: detect-empty-files
        name: Detect empty files
        language: python
        entry: python pre_commit_hooks/detect_empty_files.py
        files: ^Handleiding\/.*\.rst$
      - id: check-rst
        name: Lint reStructuredText files
        language: python
        entry: rstcheck
        files: ^Handleiding\/
        additional_dependencies:
          - rstcheck==6.2.4
          - rstcheck[sphinx]==6.2.4
        args:
          - --report-level
          - WARNING
      - id: check-brand-names
        name: Check brand names
        language: python
        entry: python pre_commit_hooks/check_brand_names.py
        files: \.rst$
        args:
          - -b
          - CURQ,GitHub
      - id: check-media-directory
        name: Check all media is in media directory
        language: python
        entry: python pre_commit_hooks/check_media_directory.py
        files: ^Handleiding\/.*(\.png|\.jpg|\.jpeg)$
